04:33:09 PM: DEBUG [logger_base.py:12] Message from the level debug
04:33:09 PM: INFO [logger_base.py:13] Message from the level info
04:33:09 PM: WARNING [logger_base.py:14] Message from the level warning
04:33:09 PM: ERROR [logger_base.py:15] Message from the level error
04:33:09 PM: CRITICAL [logger_base.py:16] Message from the level critical
05:19:12 PM: DEBUG [connection.py:28] Creation of the pool in the project user lab was successful :<psycopg2.pool.SimpleConnectionPool object at 0x7f3344caaeb0>
05:19:12 PM: DEBUG [connection.py:40] Connection got it from the pool : <connection object at 0x7f3344c6aa40; dsn: 'user=linuxdev password=xxx dbname=test_db_udemy host=localhost port=5432', closed: 0>
05:23:25 PM: DEBUG [connection.py:28] Creation of the pool in the project user lab was successful :<psycopg2.pool.SimpleConnectionPool object at 0x7f13e7bcb250>
05:23:25 PM: DEBUG [connection.py:40] Connection got it from the pool : <connection object at 0x7f13e6925040; dsn: 'user=linuxdev password=xxx dbname=test_db_udemy host=localhost port=5432', closed: 0>
05:23:25 PM: DEBUG [connection.py:46] We put back the object connection to the pool : <connection object at 0x7f13e6925040; dsn: 'user=linuxdev password=xxx dbname=test_db_udemy host=localhost port=5432', closed: 0>
05:31:12 PM: DEBUG [connection.py:28] Creation of the pool in the project user lab was successful :<psycopg2.pool.SimpleConnectionPool object at 0x7f7be56b8190>
05:31:12 PM: DEBUG [connection.py:40] Connection got it from the pool : <connection object at 0x7f7be4355040; dsn: 'user=linuxdev password=xxx dbname=test_db_udemy host=localhost port=5432', closed: 0>
05:31:12 PM: DEBUG [connection.py:46] We put back the object connection to the pool : <connection object at 0x7f7be4355040; dsn: 'user=linuxdev password=xxx dbname=test_db_udemy host=localhost port=5432', closed: 0>
05:32:00 PM: DEBUG [connection.py:28] Creation of the pool in the project user lab was successful :<psycopg2.pool.SimpleConnectionPool object at 0x7f0426567190>
05:32:00 PM: DEBUG [connection.py:40] Connection got it from the pool : <connection object at 0x7f0425204040; dsn: 'user=linuxdev password=xxx dbname=test_db_udemy host=localhost port=5432', closed: 0>
05:32:00 PM: DEBUG [connection.py:46] We put back the object connection to the pool : <connection object at 0x7f0425204040; dsn: 'user=linuxdev password=xxx dbname=test_db_udemy host=localhost port=5432', closed: 0>
05:32:00 PM: DEBUG [connection.py:51] all connection from the pool were closed
